// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;

namespace deMinimis
{
    public partial class JednoduchaPodpora
    {
        static Response.Ciselnik[] formy = deMinimis.DeMinimisCalls.Ciselnik("c_forma_podpory");
        static Response.Ciselnik[] priznaky_podpory = deMinimis.DeMinimisCalls.Ciselnik("c_priznaky_podpory");
        static Response.Ciselnik[] stav_podpory = deMinimis.DeMinimisCalls.Ciselnik("c_stav_podpory");
        static Response.Ciselnik[] duvod_zruseni_podpory = deMinimis.DeMinimisCalls.Ciselnik("c_duvod_zruseni_podpory");
        static Response.Ciselnik[] pravni_akt_poskytnuti = deMinimis.DeMinimisCalls.Ciselnik("c_pravni_akt_poskytnuti");

        public static JednoduchaPodpora FromJson(string zaznam)
        {
            if (string.IsNullOrWhiteSpace(zaznam))
                return null;
            if (!zaznam.Trim().StartsWith("{"))
                return null;
            zaznam = zaznam.Trim();
            if (zaznam.EndsWith(","))
                zaznam = zaznam.Remove(zaznam.Length - 1);

            OldCl i = Newtonsoft.Json.JsonConvert.DeserializeObject<OldCl>(zaznam);

            JednoduchaPodpora p = new JednoduchaPodpora();
            //p.CjPrijemce = i.;
            p.Edidat = i.Edidat;
            p.Ico =  i.Ico.ToString().PadLeft(8,'0');
            p.Id = i.Id;
            p.Insdat = i.Insdat;
            p.PodporaCzk = (decimal)i.PodporaCzk;
            p.PodporaDatum = i.PodporaDatum;
            p.PodporaEur = (decimal)i.PodporaEur;
            p.PodporaForma_Kod = i.PodporaFormaKod;
            p.PodporaFormaText = i.PodporaFormaText;
            p.PodporaUcel = i.PodporaUcel;
            p.PoskytovatelOjm = i.PoskytovatelOjm;
            p.Poskytovatel_SZRId = i.OrgSzrid;
            p.PravniAktPoskytnutiId = i.PravniAktPoskytnutiId;
            p.PravniAktPoskytnutiText = i.PravniAktPoskytnutiText;
            p.ProjektId = i.ProjektId;

            p.StavKod = i.StavKod;
            p.StavKodText = i.StavKodText;
            p.Prijemce_SZRId = i.Subjektid;
            return p;
        }
        public static List<JednoduchaPodpora> FromAPI(deMinimis.Response.Detail.Response zaznam)
        {
            if (zaznam == null)
                return null;
            if (zaznam.seznam_subjektu == null)
                return null;

            if (zaznam.seznam_subjektu?.Length < 1)
                return null;

            List<JednoduchaPodpora> podpory = new List<JednoduchaPodpora>();
            foreach (var s in zaznam.seznam_subjektu)
            {
                foreach (var i in s.seznam_podpor)
                {
                    JednoduchaPodpora p = new JednoduchaPodpora();
                    p.CjPrijemce = i.cj_prijemce;
                    p.Edidat = i.edidat;
                    p.Ico = s.seznam_identifikatoru.Where(m => m.Value == "ICO").OrderByDescending(o => o.platnost_od).FirstOrDefault()?.Value;
                    p.Id = i.id_podpory;
                    p.Insdat = i.insdat;
                    p.PodporaCzk = i.castka_kc;
                    p.PodporaDatum = i.datum_prideleni;
                    p.PodporaEur = i.castka_euro;
                    p.PodporaForma_Kod = i.forma_podpory;
                    p.PodporaFormaText = formy.FirstOrDefault(m => m.kod == i.forma_podpory)?.nazev;
                    p.PodporaUcel = i.ucel_podpory;
                    p.PoskytovatelOjm = i.poskytovatel_ojm;
                    p.Poskytovatel_SZRId = i.poskytovatel_id;
                    p.PravniAktPoskytnutiId = i.pravni_akt_poskytnuti;
                    p.PravniAktPoskytnutiText = pravni_akt_poskytnuti.FirstOrDefault(m => m.kod == i.pravni_akt_poskytnuti)?.nazev;
                    p.ProjektId = i.cj_poskytovatel;

                    p.RezimPodporyId = i.rezim_podpory.adhoc ? "Adhoc podpora" : (string.IsNullOrEmpty(i.rezim_podpory.nazev) ? "režim podpory" : i.rezim_podpory.nazev);
                    p.StavKod = i.stav;
                    p.StavKodText = stav_podpory.FirstOrDefault(m => m.kod == i.stav)?.nazev;
                    p.Prijemce_SZRId = s.subjektid;
                    podpory.Add(p);
                }
            }
            return podpory;
        }

        public JednoduchaPodpora() { }

        public int Id { get; set; }
        public int Prijemce_SZRId { get; set; }
        public string Ico { get; set; }
        public string RdmOblastKod { get; set; }
        public decimal PodporaCzk { get; set; }
        public decimal PodporaEur { get; set; }
        public DateTime PodporaDatum { get; set; }
        public int PodporaForma_Kod { get; set; }
        public string PodporaFormaText { get; set; }
        public string PodporaUcel { get; set; }
        public string ProjektId { get; set; }
        public string CjPrijemce { get; set; }
        public int StavKod { get; set; }
        public string StavKodText { get; set; }
        public DateTime? Insdat { get; set; }
        public DateTime? Edidat { get; set; }
        public int Poskytovatel_SZRId { get; set; }
        public string PoskytovatelOjm { get; set; }
        public int PravniAktPoskytnutiId { get; set; }
        public string PravniAktPoskytnutiText { get; set; }
        public string RezimPodporyId { get; set; }
    }
}