YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=ivan-adamec /playlist=UUlj4ZIIqsyAhwJL_s685MMA
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=hana-aulicka-jirovcova /playlist=UUAj7vOS9MuS2NGmnC3mMRaA
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=andrej-babis /playlist=UUQEPR23yCIME2NcyNvBqjdg
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=tomas-czernin /playlist=PLiD83AlngMPoEqWVi6dlAEAU7uhejUb2F
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=dominik-feri /playlist=UUlj4ZIIqsyAhwJL_s685MMA
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=petr-fiala /playlist=UUbeZpBWNuqjd8VFKpoKw70g
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=jan-grolich-1 /playlist=UUz2vCoCB2GAxBTZCKY0wliQ
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=vaclav-hampl /playlist=UUoQGYUft2dmdBNwBo_ngerQ
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=karel-havlicek-3 /playlist=UUBb1XL5nvz7u3Inzhi_UYxA
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=radek-holomcik /playlist=UULlGqNDcUCUD1Lvye9FZLZQ
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=zdenek-hrib /playlist=UUZVRrw9rZYFSgsPVwgga0JQ
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=marian-jurecka /playlist=UUJdA5Spuj65aoorD0YcQISg
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=martin-kolovratnik /playlist=UUfmOkf6Yf6Gk_rfKOSNw5og
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=ludek-niedermayer /playlist=UUSBf3rsiQWsGtSYDglTWYfQ
YoutubeToVyjadreniPolitiku.exe /mp3path=e:\Data\Web\Mp3 /osobaid=tomio-okamura /playlist=UUe0c2rUjCHtQSf2XY7ulCQA
